export const HEADER_FIXED = "HEADER_FIXED"
export const HEADER_UNFIXED = "HEADER_UNFIXED"

export const SET_HEADER_FIXED = "SET_HEADDER_FIXED"
export const SET_HEADER_UNFIXED = "SET_HEADDER_UNFIXED"

export const ADD_FILE_TO_CART = "ADD_FILE_TO_CART"
export const ADD_DOC_TO_CART = "ADD_DOC_TO_CART"

export const REMOVE_FILE_FROM_CART = "REMOVE_FILE_FROM_CART"
export const REMOVE_DOC_FROM_CART = "REMOVE_DOC_FROM_CART"

export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const REGISTER = "REGISTER"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
